name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - mlflow=2.1.1
  - hydra-core=1.0.6
  - pip:
      - wandb==0.13.9
      - hydra-joblib-launcher==1.1.2
